[2023-05-25 15:59:02,850][src.utils][INFO] - Git sha: cb48181a15e2c8c1bbfe2c384261548e9ed14a3a
[2023-05-25 15:59:02,859][src.utils][INFO] - Changed files: ['conf/tasks/compute_dependence_with_base_changes.yaml', 'src/evals/prompts/distribution_prompt.py']
[2023-05-25 15:59:02,866][src.utils][INFO] - Git diff:
diff --git a/conf/tasks/compute_dependence_with_base_changes.yaml b/conf/tasks/compute_dependence_with_base_changes.yaml
index 366c20f..45aec6d 100644
--- a/conf/tasks/compute_dependence_with_base_changes.yaml
+++ b/conf/tasks/compute_dependence_with_base_changes.yaml
@@ -3,5 +3,5 @@ model: gpt-3.5-turbo
 num_shots: 4
 on_ambiguous_sequences: true
 num_samples: 1
-distribution: default
+distribution: self-consistency
 shot_method: random
diff --git a/src/evals/prompts/distribution_prompt.py b/src/evals/prompts/distribution_prompt.py
index f409b87..639aca9 100644
--- a/src/evals/prompts/distribution_prompt.py
+++ b/src/evals/prompts/distribution_prompt.py
@@ -4,21 +4,70 @@ different distbutions. This should be easiest to do by adding to the DISTRIBUTIO
 dictionary in this file.
 """
 
-SELF_CONTINUATION_PROMPT = """
+SELF_CONTINUATION_PROMPT = (
+"""
 In your opinion, what is the most likely continuation of the following sequence?
 Give your response as a number, with no additional commentary.
 """
+)
+SELF_EXPLANATION_PROMPT = (
+"""
+In your opinion, what is the most likely function which generated the following sequence?
+Assume the first number was generated by f(0), the second by f(1), and so on.
+The function should output the number in decimal form.
+Give your response in the format:
+Explanation: <function>
+"""
+)
+
+SIMULATION_CONTINUATION_PROMPT = (
+"""
+Please choose the continuation of the following sequence which you think is most likely.
+Give your response as a number, with no additional commentary.
+"""
+)
 
-SELF_EXPLANATION_PROMPT = """In your opinion, what is the most likely function which generated the following sequence?
+SIMULATION_EXPLANATION_PROMPT = (
+"""
+Please choose the function which you think is most likely to have generated the following sequence.
 Assume the first number was generated by f(0), the second by f(1), and so on.
 The function should output the number in decimal form.
 Give your response in the format:
 Explanation: <function>
 """
+)
+
+CONSISTENT_CONTINUATION_PROMPT = (
+"""
+Choose a continuation of the following sequence.
+You will be separately asked to choose a function which generated the sequence. 
+Please choose a continuation which is consistent with the function you will choose.
+Give your response as a number, with no additional commentary.
+"""
+)
 
+CONSISTENT_EXPLANATION_PROMPT = (
+"""
+Choose a function which generated the following sequence.
+You will be separately asked to choose a continuation of the sequence.
+Please choose a function which is consistent with the continuation you will choose.
+Assume the first number was generated by f(0), the second by f(1), and so on.
+The function should output the number in decimal form.
+Give your response in the format:
+Explanation: <function>
+"""
+)
 DISTRIBUTIONS = {
     "default": {
         "continuation": SELF_CONTINUATION_PROMPT,
         "explanation": SELF_EXPLANATION_PROMPT,
-    }
+    },
+    "self-simulation": {
+        "continuation": SIMULATION_CONTINUATION_PROMPT,
+        "explanation": SIMULATION_EXPLANATION_PROMPT,
+    },
+    "self-consistency": {
+        "continuation": CONSISTENT_CONTINUATION_PROMPT,
+        "explanation": CONSISTENT_EXPLANATION_PROMPT,
+    },
 }
[2023-05-25 16:00:04,042][openai][INFO] - error_code=None error_message='That model is currently overloaded with other requests. You can retry your request, or contact us through our help center at help.openai.com if the error persists. (Please include the request ID de65df0c5c97d5aee74c124f62da01f8 in your message.)' error_param=None error_type=server_error message='OpenAI API error received' stream_error=False
[2023-05-25 16:01:05,047][openai][INFO] - error_code=None error_message='That model is currently overloaded with other requests. You can retry your request, or contact us through our help center at help.openai.com if the error persists. (Please include the request ID aeaac5a9b943f52247f002400965aa9b in your message.)' error_param=None error_type=server_error message='OpenAI API error received' stream_error=False
